language: node_js
node_js:
- '0.8'
- '0.10'
before_script:
- npm install
- npm install -g bower grunt-cli
- bower install

after_script:
- grunt build
- cd dist
- cp -R app/images dist/public
deploy:
  provider: heroku
  app: reversibot
  api_key:
    secure: AWj8LWtj7pIXQLCJueoskWmZP5KWrZtfpttWj905NvcKjFK+R+NgcryoyL1cO4rW4lydGQK5IIZXEpMTcHxaU9gtfcHBkDflQtxQAz1lnLlCveXZnkOU38qoeH6IBNfusZO6tSuyeS53khFLTCoX60bUDVLSxCjZGGG8ix4oQgM=
