language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
before_deploy:
- grunt build
- cp -R app/images dist/public
- cp -R dist/* .
deploy:
  provider: heroku
  app: reversibot
  strategy: git
  api_key:
    secure: AWj8LWtj7pIXQLCJueoskWmZP5KWrZtfpttWj905NvcKjFK+R+NgcryoyL1cO4rW4lydGQK5IIZXEpMTcHxaU9gtfcHBkDflQtxQAz1lnLlCveXZnkOU38qoeH6IBNfusZO6tSuyeS53khFLTCoX60bUDVLSxCjZGGG8ix4oQgM=
