language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
before_deploy:
- grunt build
- cp -R app/images dist/public
- cd dist
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:reversibot.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- yes | git push heroku master
deploy:
  provider: heroku
  app: reversibot
  strategy: git
  api_key:
    secure: AWj8LWtj7pIXQLCJueoskWmZP5KWrZtfpttWj905NvcKjFK+R+NgcryoyL1cO4rW4lydGQK5IIZXEpMTcHxaU9gtfcHBkDflQtxQAz1lnLlCveXZnkOU38qoeH6IBNfusZO6tSuyeS53khFLTCoX60bUDVLSxCjZGGG8ix4oQgM=
